### ISSUE TITLE
Lista

### ISSUE THREAD

**Issue by renatobarramansa** [Prof-Rodrigo-Silva/PortugolStudioListaExercicios1#1]
Boa tarde professor, o senhor teria a lista com os exercícios, para disponibilizar ?

**Comment by andergraciano** [comment]
@renatobarramansa Olá Renato!
A lista de exercícios está localizada no mesmo repositórios com os exercícios resolvidos. Segue o link: https://github.com/Prof-Rodrigo-Silva/Atividade-PortugolStudio . É o arquivo PDF localizado no final da página, nomeado "APOSTILA PSEUDO ALGORITMO.pdf".

**Comment by renatobarramansa** [comment]
Muito obrigado,consegui localizar, tenho aprendido muito com seu curso ! Que Jesus te abençoe hoje e sempre !
